const modalKeys = {
  LaboratoryData: [
    "Sodium",
    "Potassium",
    "Chloride",
    "Bicarbonate",
    "BUN",
    "Creatinine",
    "Calcium",
    "Ionized Calcium",
    "Magnesium",
    "Phosphorous",
    "pH",
    "Filtration Fraction",
    "Calcium Final Post Filter",
    "Lactate",
    "Albumin",
    "WBC",
    "Hemoglobin",
    "Hematocrit",
    "Platelet Count",
    "PC02",
    "Granular Casts",
    "Renal Epithelial Casts",
    "Hyaline Casts",
    "Blood Culture",
    "Urine Culture"
  ],
  "Input/Output": [
    "Acetylcysteine",
    "Fentanyl",
    "Vasopressin",
    "Cisatracurium",
    "Midazolam",
    "Norepinephrine",
    "Normal Saline Bolus",
    "Normal Saline Carrier",
    "Meropenem",
    "Levofloxacin",
    "Citrate",
    "Calcium Chloride",
    "Calcium Gluconate",
    "Albumin",
    "Vancomycin",
    "Tube Feeds",
    "Total Input",
    "Net Input/Output",
    "Cumulative Input/Output"
  ],
  Vitals: [
    "Temperature",
    "Heart Rate",
    "Respiratory Rate",
    "Blood Pressure",
    "Weight"
  ],
  Medications: ["Scheduled", "Infusions"]
};

export default modalKeys;
